const Small = {
    home:[
      { i: 'intro', x: 0, y: 0, w: 4, h: 1 },
      { i: 'map', x: 0, y: 1, w: 2, h: 1},
      { i: 'socialMedia', x: 2, y: 1, w: 2, h: 1 },
      { i: 'contact', x: 0, y: 2, w: 4, h: 1},
      { i: 'blog', x: 0, y: 3,w: 4, h: 1 },
      { i: 'project1', x: 0, y: 4, w: 2, h: 2 },
      { i: 'project2', x: 2, y: 4, w: 2, h: 2 },
      { i: 'project3', x: 0, y: 5, w: 4, h: 1},
      { i: 'darkModeToggle', x: 0, y: 6, w: 2, h: 1},
      { i: 'git', x: 2, y: 6, w: 2, h: 1},
    ],
    projects:[
      { i: 'intro', x: 0, y: 2, w: 4, h: 1 },
      { i: 'map', x: 2, y: 3, w: 2, h: 1},
      { i: 'contact', x: 0, y: 5, w: 4, h: 1},
      { i: 'blog', x: 0, y: 4, w: 4, h: 1 },
      { i: 'project1', x: 0, y: 1, w: 2, h: 2 },
      { i: 'project2', x: 2, y: 1, w: 2, h: 2 },
      { i: 'project3', x: 0, y: 0,   w: 4, h: 1},
      { i: 'darkModeToggle', x: 2, y: 2, w: 2, h: 1},
      { i: 'git', x: 0, y: 2, w: 2, h: 1 },
      { i: 'socialMedia', x: 0, y: 3, w: 2, h: 1 },
    ],
    contact:[
      { i: 'contact', x: 0, y: 0, w: 4, h: 1 },
      { i: 'map', x: 0, y: 1, w: 2, h: 1},
      { i: 'socialMedia', x: 2, y: 1, w: 2, h: 1 },
      { i: 'intro', x: 0, y: 2, w: 4, h: 1},
      { i: 'blog', x: 0, y: 3,w: 4, h: 1 },
      { i: 'project1', x: 0, y: 4, w: 2, h: 2 },
      { i: 'project2', x: 2, y: 4, w: 2, h: 2 },
      { i: 'project3', x: 0, y: 5, w: 4, h: 1},
      { i: 'darkModeToggle', x: 0, y: 6, w: 2, h: 1},
      { i: 'git', x: 2, y: 6, w: 2, h: 1},
    ],
    about:[
      { i: 'intro', x: 0, y: 0, w: 4, h: 1 },
      { i: 'map', x: 0, y: 2, w: 2, h: 1},
      { i: 'socialMedia', x: 2, y: 2, w: 2, h: 1 },
      { i: 'contact', x: 0, y: 3, w: 4, h: 1},
      { i: 'blog', x: 0, y: 1, w: 4, h: 1 },
      { i: 'project1', x: 0, y: 5, w: 2, h: 2 },
      { i: 'project2', x: 2, y: 5, w: 2, h: 2 },
      { i: 'project3', x: 0, y: 6, w: 4, h: 1},
      { i: 'darkModeToggle', x: 0, y: 7, w: 2, h: 1},
      { i: 'git', x: 2, y: 7, w: 2, h: 1},
    ],
  }

  export default Small;